// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/google/wire"
	"library-be/app/controller"
	"library-be/app/repository"
	"library-be/app/service"
	"library-be/config"
)

// Injectors from injector.go:

func Initialized() *Initialization {
	environment := config.InitEnvironment()
	db := config.InitDatabase(environment)
	authorRepository := repository.NewAuthorRepository(db)
	authorService := service.NewAuthorService(authorRepository)
	authorController := controller.NewAuthorController(authorService)
	publisherRepository := repository.NewPublisherRepository(db)
	publisherService := service.NewPublisherService(publisherRepository)
	publisherController := controller.NewPublisherController(publisherService)
	bookRepository := repository.NewBookRepository(db)
	bookService := service.NewBookService(authorRepository, bookRepository)
	bookController := controller.NewBookController(bookService)
	authRepository := repository.NewAuthRepository(db)
	authService := service.NewAuthService(authRepository)
	authController := controller.NewAuthController(authService)
	initialization := NewInitialization(authorController, publisherController, bookController, authController)
	return initialization
}

// injector.go:

var authorSet = wire.NewSet(controller.NewAuthorController, service.NewAuthorService, repository.NewAuthorRepository)

var publisherSet = wire.NewSet(controller.NewPublisherController, service.NewPublisherService, repository.NewPublisherRepository)

var bookSet = wire.NewSet(controller.NewBookController, service.NewBookService, repository.NewBookRepository)

var authSet = wire.NewSet(controller.NewAuthController, service.NewAuthService, repository.NewAuthRepository)
